const Constants = {
  /* fonts */
  fontRegular: 'SFProDisplay-Regular',
  fontBold: 'SFProDisplay-Bold',
  /* screens */
  splashScreen: 'Splash',
  loginScreen: 'Login',
  signUpScreen: 'SignUp',
  OTP: 'OTP',
  forgetPasswordScreen: 'ForgetPassword',
  ResetPassword: 'ResetPassword',
  termsAndConditionsScreen: 'TermsAndConditions',
  faqsScreen: 'Faqs',
  helpScreen: 'Help',
  favoritePetsScreen: 'FavoritePets',
  orderHistoryScreen: 'OrderHistory',
  settingsScreen: 'Settings',
  AddPets: 'AddPets',
  updatesScreen: 'Updates',
  petDetailsScreen: 'PetDetails',
  searchScreen: 'Search',
  selectDateScreen: 'SelectDate',
  selectTimeScreen: 'SelectTime',
  confirmRentScreen: 'ConfirmRent',
  chatHistoryScreen: 'ChatHistory',
  chatScreen: 'Chat',
  myProfileScreen: 'MyProfile',
  profileSettingsScreen: 'ProfileSettings',
  OtherUserProfile: 'OtherUserProfile',
  Stories: 'Stories',
  PaymentScreen: 'PaymentScreen',
  AddNewCard: 'AddNewCard',

  /* tabs */
  tabNavigatorScreen: 'TabNavigator',
  homeScreen: 'Home',
  nearbyScreen: 'Nearby',
  demoScreen: 'Demo',
  moreScreen: 'More',

  // ------------- API-URLS------------------
  // for auth
  // baseURL: "http://petpal-app.com/api/v1/",
  // imageURL: "http://petpal-app.com/",
  baseURL: 'https://pet-pal.reignsol.net/api/v1/',
  imageURL: 'https://pet-pal.reignsol.net/',
  signUpURL: 'auth/register',
  googleLoginURL: 'auth/social/google',
  facebookLoginURL: 'auth/social/facebook',
  AppleaLoginURL: 'auth/social/apple',
  loginURL: 'auth/login',
  verifyOtpURL: 'auth/verify-otp',
  resendOtpURL: 'auth/resend-otp',
  forgotPasswordURL: 'auth/forgot-password',
  resetPasswordURL: 'auth/reset-password',
  getProfileURL: 'auth/getProfile',
  updateProfileURL: 'auth/update-profile',
  signOutURL: 'auth/sign-out',
  //
  favouritePets: 'favourite',
  pets: 'pets',
  petsView: 'pets/view',
  breed: 'breeds/getBreedByCategory',
  category: 'category/getAllCategory',
  addData: 'pets/add',
  faq: 'general/contents',
  terms: 'general/contents',
  help: 'general/contents',
  updates: 'general/settings/updates',
  notifications: 'notification',
  nearBy: 'pets/getPetNearyou',
  story: 'story',
  orderHistory: 'order/orderHistory',
  customerCategoriesURL: 'customer/categories',
  customerViewCategoriesURL: 'customer/view-category?',
  customerRatingsURL: 'customer/ratings',
  contentsURL: 'contents',
  notificationsURL: 'notifications',
  logoutURL: 'auth/sign-out',
  servies: 'auth/services',
  getAllVendorCategories: 'vendors/categories',
  getAllCustomerCategories: 'customer/categories',
  postJob: 'customer/jobs/create',
  getAllJobs: 'vendors/getAllJobs',
  getJobsByCategory: 'vendors/getJobsByCategory?',
  getFilter: 'pets/get-filters',
  searchFilter: 'pets/search-filter',
  getvendorAround: 'customer/vendorAroundYou?',
  getTopSerVices: 'customer/getAllVendors',
  getPetDetails: 'pets/view',
  addRemoveFav: 'favourite/add-remove',
  otheruser: 'auth/userProfile/',
  color: 'colors',
  Breed: 'preferences/pets-lists',
  Activity: 'preferences/pets-lists',
  GetDocumentTypes: 'general/settings/alldocumentTypes',
  PetRatinbg: 'pets/add-rating',
  RatingList: 'pets/get-comments',
  GetBookedSlots: 'pets/getPetsStatusbyDate',
  Order: 'order/proceed',
  StoryView: 'story/mark-view',
  showPet: 'pets/view',
  CardAdd: 'cards/add',
  Cardslist: 'cards/',

  // others
  accessToken: 'accessToken',

  // region firebase key
  FIREBASE_PATH_STRING: '1QyufxP3T0P9J4gV6rUe0o1EW9WzIs5jQWJ5hQN71zQo',
  FIREBASE_CHAT: 'Chat',
  FIREBASE_MESSAGES: 'messages',
  FIREBASE_USERS: 'Users',
  FIREBASE_CHATHEADS: 'ChatHeads',
  FIREBASE_READ: 'read',
  FIREBASE_TOKEN: 'Tokens',
  FCM: 'https://fcm.googleapis.com/fcm/send',
};

export default Constants;
